### ISSUE TITLE
invalid JSON for config.json

### ISSUE THREAD

**Issue by joe8mofo** [nicholasrobinson/homebridge-smartcielo#12]
Why is the example config.json invalid?

Initializing HAP-NodeJS v0.9.4...
[5/18/2021, 3:49:53 AM] There was a problem reading your config.json file.
[5/18/2021, 3:49:53 AM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[5/18/2021, 3:49:53 AM] 
SyntaxError: Unexpected token : in JSON at position 13
    at JSON.parse (<anonymous>)
    at Function.loadConfig (/usr/lib/node_modules/homebridge/src/server.ts:212:21)
    at new Server (/usr/lib/node_modules/homebridge/src/server.ts:92:26)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:79:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

**Comment by nicholasrobinson** [comment]
Per the error output:

`SyntaxError: Unexpected token : in JSON at position 13`

it seems that you have invalid JSON. Please try pasting your config.json file here to validate it: http://jsonlint.com

You’ll have to share your `config.json` in order to diagnose the issue, but you may be able to resolve the issue yourself using the above tool.

Note: If you do share your config, please remove any compromising information (usernames, passwords etc.)

Note 2: There is no “working” `config.json` in this project, only a snippet in the README that should be combined with an already working homebridge config.

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/homebridge-smartcielo/issues/22
